### PR TITLE
Added dijkstras program in python

### PR DESCRIPTION
**Pull request by Kavyapriyakp**
A python program to demonstrate the working of dijkstra's algorithm is added

### CODE REVIEW

**Comment by rohan8594** [comment]
@Kavyapriyakp I'll review and merge this over the weekend. Can you pls in the meantime create a separate issue mentioning this algorithm and reference that issue on here. So that no one adds this again.

**Comment by rohan8594** [comment]
Also pls read the contribution guide. This solution should go under the folder `algorithms -> Graphs`

**Review by rohan8594 — CHANGES_REQUESTED** [review]
@Kavyapriyakp Please create a folder `Graphs` under the folder `algorithms` and put this file inside that. Will merge this PR then.

**Comment by Kavyapriyakp** [comment]
@rohan8594 I'll do the necessary!

**Pull request closed without merging**
