### PR TITLE
Create BubbleSortOptimized

### PR DESCRIPTION
**Pull request by cpsggisc**
Improves on the non-optimised version in 2 ways:
- if within a single pass there is no swap, means array is sorted, hence terminate
- after each pass, need not consider largest last item since it is already in place

### CODE REVIEW

**Review by rohan8594 — CHANGES_REQUESTED** [review]
This solution is not correct. Try executing it locally with the test case you've used and see what you get. The array will not be sorted.

**Comment by cpsggisc** [comment]
sorry fixed indentation level due to different tab/space settings on my ide thks!

**Review by rohan8594 — APPROVED** [review]
@dhsgisc Thanks for the contribution. Nice bit of optimization.

**Comment by rohan8594** [comment]
@all-contributors please add @dhsgisc for code

**Pull request merged**
