### PR TITLE
Create 56_Merge_common_intervals.java

### PR DESCRIPTION
**Pull request by cheshtaaagarrwal**
Added merge common interval code question 56

### CODE REVIEW

**Comment by rohan8594** [comment]
@cheshtaaagarrwal I'll review and merge this over the weekend. Can you pls in the meantime create a separate issue mentioning this algorithm and reference that issue on here. So that no one adds this again.

**Comment by cheshtaaagarrwal** [comment]
I have added an issue but pls can you merge it sooner? Actually its for hacktober fest.

**Review by rohan8594 — APPROVED** [review]

**Comment by rohan8594** [comment]
@all-contributors-bot please add @cheshtaaagarrwal for code

**Comment by rohan8594** [comment]
@all-contributors please add @cheshtaaagarrwal for code

**Pull request merged**
